# cargo-dist config — https://opensource.axo.dev/cargo-dist/

[workspace]
members = ["cargo:."]

# Config for 'dist'
[dist]
cargo-dist-version = "0.28.0"
ci = "github"
installers = ["shell"]
targets = [
  "x86_64-unknown-linux-gnu",
  "aarch64-unknown-linux-gnu",
]
unix-archive = ".tar.xz"
pr-run-mode = "plan"
install-path = "CARGO_HOME"
